// This file is automatically generated by build.rs

pub const SHOKEN_WEBAPI_STOCK: &'static str = "";
pub const SHOKEN_WEBAPI_GOOGLE_OAUTH_CLIENT_ID: &'static str = "";
pub const SHOKEN_WEBAPI_GOOGLE_OAUTH_CLIENT_SECRET_ID: &'static str = "";
pub const SHOKEN_WEBAPI_REDIRECT_URL: &'static str = "http://localhost:8080/shoken-webapp-wasm/";
