// This file is automatically generated by build.rs

pub const SHOKEN_WEBAPI_STOCK: &'static str = "http://127.0.0.1:8000/stock/";
pub const SHOKEN_WEBAPI_OAUTH_GOOGLE: &'static str = "http://127.0.0.1:8000/oauth/google";
