// This file is automatically generated by build.rs

pub const SHOKEN_WEBAPI_STOCK: &'static str = "https://shoken-webapp-api-b4a1.shuttle.app/stock/";
pub const SHOKEN_WEBAPI_OAUTH_GOOGLE: &'static str =
    "https://shoken-webapp-api-b4a1.shuttle.app/oauth/google";
