name: Deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      RUST_BACKTRACE: 1
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Install Trunk
        uses: jetli/trunk-action@v0.1.0
      - name: Generate env.rs
        run: |
          echo "pub struct Env {" > src/env.rs
          echo "    pub const SHOKEN_WEBAPI_GOOGLE_OAUTH_CLIENT_ID: &str = \"${{ secrets.SHOKEN_WEBAPI_GOOGLE_OAUTH_CLIENT_ID }}\";" >> src/env.rs
          echo "    pub const SHOKEN_WEBAPI_GOOGLE_OAUTH_CLIENT_SECRET_ID: &str = \"${{ secrets.SHOKEN_WEBAPI_GOOGLE_OAUTH_CLIENT_SECRET_ID }}\";" >> src/env.rs
          echo "    pub const SHOKEN_WEBAPI_OAUTH_GOOGLE: &str = \"${{ secrets.SHOKEN_WEBAPI_OAUTH_GOOGLE }}\";" >> src/env.rs
          echo "    pub const SHOKEN_WEBAPI_REDIRECT_URL: &str = \"${{ secrets.SHOKEN_WEBAPI_REDIRECT_URL }}\";" >> src/env.rs
          echo "    pub const SHOKEN_WEBAPI_STOCK: &str = \"${{ secrets.SHOKEN_WEBAPI_STOCK }}\";" >> src/env.rs
          echo "}" >> src/env.rs
      - name: Clean Build
        run: make clean && make build
      - name: Copy 404.html
        run: cp 404.html ./dist/404.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist